/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modul2;

/**
 *
 * @author ADMIN
 */
public class Tugas_modul2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tugas_modul2.class.getName());

    /**
     * Creates new form Tugas_modul2
     */
    public Tugas_modul2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Seks = new javax.swing.ButtonGroup();
        lblNama = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        lblGPokok = new javax.swing.JLabel();
        lblSeks = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lbljmlhanak = new javax.swing.JLabel();
        txtjmlhanak = new javax.swing.JTextField();
        txtgajip = new javax.swing.JTextField();
        rdopria = new javax.swing.JRadioButton();
        rdowanita = new javax.swing.JRadioButton();
        chkmenikah = new javax.swing.JCheckBox();
        lblpasangan = new javax.swing.JLabel();
        txtnamapasangan = new javax.swing.JTextField();
        btncount = new javax.swing.JButton();
        lblGajiTotal = new javax.swing.JLabel();
        txtgajit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNama.setText("Nama Pegawai");

        lblGPokok.setText("Gaji Pokok");

        lblSeks.setText("Seks");

        lblStatus.setText("Status");

        lbljmlhanak.setText("Jumlah Anak");

        txtjmlhanak.setEditable(false);
        txtjmlhanak.setEnabled(false);
        txtjmlhanak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjmlhanakActionPerformed(evt);
            }
        });

        txtgajip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgajipActionPerformed(evt);
            }
        });

        Seks.add(rdopria);
        rdopria.setText("Pria");
        rdopria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdopriaActionPerformed(evt);
            }
        });

        Seks.add(rdowanita);
        rdowanita.setText("Wanita");
        rdowanita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdowanitaActionPerformed(evt);
            }
        });

        chkmenikah.setText("Menikah");
        chkmenikah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkmenikahActionPerformed(evt);
            }
        });

        lblpasangan.setText("Nama Suami");

        btncount.setText("HItung Gaji Total");
        btncount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncountActionPerformed(evt);
            }
        });

        lblGajiTotal.setText("Gaji Total");

        txtgajit.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblStatus))
                                .addGap(65, 65, 65))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGPokok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSeks))
                                .addGap(103, 103, 103)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btncount)
                                .addComponent(lblpasangan, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(65, 65, 65)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGajiTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnama, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtgajip, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdopria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdowanita))
                            .addComponent(chkmenikah, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbljmlhanak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(txtjmlhanak, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtnamapasangan)
                    .addComponent(txtgajit))
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGPokok)
                    .addComponent(txtgajip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeks)
                    .addComponent(rdopria)
                    .addComponent(rdowanita))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(chkmenikah))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbljmlhanak)
                    .addComponent(txtjmlhanak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpasangan)
                    .addComponent(txtnamapasangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btncount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGajiTotal)
                    .addComponent(txtgajit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtgajipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgajipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgajipActionPerformed

    private void rdopriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdopriaActionPerformed
        // TODO add your handling code here:
        if (rdopria.isSelected()) {
            lblpasangan.setText("Nama Istri");
        }
    }//GEN-LAST:event_rdopriaActionPerformed

    private void btncountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncountActionPerformed
        // TODO add your handling code here:
        
        double gajiPokok = Double.parseDouble(txtgajip.getText());
        double jmlhanak = 0;
        if (chkmenikah.isSelected()) {
            jmlhanak = Double.parseDouble(txtjmlhanak.getText());
        } else {
            jmlhanak = 0;
        }
        if (jmlhanak >= 0 && jmlhanak <= 3) {
            if (jmlhanak == 3) {
            double gajiTotal = gajiPokok + (gajiPokok * 10/100 * 3);
            txtgajit.setText(Double.toString(gajiTotal));
            } else {
            double gajiTotal = gajiPokok + (gajiPokok * 10/100 * jmlhanak);
            txtgajit.setText(Double.toString(gajiTotal));
            }
        } else {
            txtgajit.setText("Error, check your input");
        }
        
    }//GEN-LAST:event_btncountActionPerformed

    private void chkmenikahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkmenikahActionPerformed
        // TODO add your handling code here:
        if (chkmenikah.isSelected()) {
            txtjmlhanak.setEditable(true);
            txtjmlhanak.setEnabled(true);
        } else {
            txtjmlhanak.setEditable(false);
            txtjmlhanak.setEnabled(false);
        }
    }//GEN-LAST:event_chkmenikahActionPerformed

    private void rdowanitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdowanitaActionPerformed
        // TODO add your handling code here:
        if (rdowanita.isSelected()) {
            lblpasangan.setText("Nama Suami");
        }
    }//GEN-LAST:event_rdowanitaActionPerformed

    private void txtjmlhanakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjmlhanakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjmlhanakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tugas_modul2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Seks;
    private javax.swing.JButton btncount;
    private javax.swing.JCheckBox chkmenikah;
    private javax.swing.JLabel lblGPokok;
    private javax.swing.JLabel lblGajiTotal;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblSeks;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lbljmlhanak;
    private javax.swing.JLabel lblpasangan;
    private javax.swing.JRadioButton rdopria;
    private javax.swing.JRadioButton rdowanita;
    private javax.swing.JTextField txtgajip;
    private javax.swing.JTextField txtgajit;
    private javax.swing.JTextField txtjmlhanak;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnamapasangan;
    // End of variables declaration//GEN-END:variables
}
