/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modul3;
import javax.swing.DefaultListModel;
/**
 *
 * @author unbk
 */
public class FDaftar extends javax.swing.JFrame {

    DefaultListModel pilih;
    /**
     * Creates new form FDaftar
     */
    public FDaftar() {
        initComponents();
        //agar mudah di tambah dan hapus
        //lstPilih dibuatkan list model
        pilih = new DefaultListModel();
        lstPilih.setModel(pilih);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPilih = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCopy = new javax.swing.JButton();
        txtKuliah = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTerpilih = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cboAngkatan = new javax.swing.JComboBox<>();
        btnHitung = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResume = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstKuliah = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Daftar Mata Kuliah");

        lstPilih.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPilihValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstPilih);

        jLabel2.setText("Mata Kuliah Terpilih");

        jLabel3.setText("Kuliah Yang Dipilih");

        btnCopy.setText(">>");
        btnCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyActionPerformed(evt);
            }
        });

        txtKuliah.setEditable(false);
        txtKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKuliahActionPerformed(evt);
            }
        });

        jLabel4.setText("Banyak Mata Kuliah Terpilih");

        txtTerpilih.setEditable(false);
        txtTerpilih.setText("0");
        txtTerpilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerpilihActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus Terpilih");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel5.setText("Angkatan");

        cboAngkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2009", "2008", "2007", "<2007" }));
        cboAngkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAngkatanActionPerformed(evt);
            }
        });

        btnHitung.setText("Hitung Biaya");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        txtResume.setEditable(false);
        txtResume.setColumns(20);
        txtResume.setRows(5);
        jScrollPane1.setViewportView(txtResume);

        lstKuliah.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Java dekstop", "Pemrograman Web", "Bahasa Inggris", "Logika dan Algoritma", "Orgnanisasi Komputer" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstKuliah.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstKuliahValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstKuliah);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCopy))
                            .addComponent(jLabel1)
                            .addComponent(btnHitung)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTerpilih, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnCopy)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTerpilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHitung)))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTerpilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerpilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerpilihActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int index = lstPilih.getSelectedIndex();
        // yang di remove adalah listDAta model-nya
        pilih.remove(index);
        int size = pilih.getSize();
        txtTerpilih.setText(Integer.toString(size));
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyActionPerformed
        // TODO add your handling code here:
        /** Menambahkan tulisan di lstKuliah yang dipilih
         *  ke dalam ListData Model pilih */
         pilih.addElement(lstKuliah.getSelectedValue().toString());
         //Setelah ditambahkan, hitung jumlah pilihan
         int size = pilih.getSize();
         txtTerpilih.setText(Integer.toString(size));
    }//GEN-LAST:event_btnCopyActionPerformed

    private void lstPilihValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPilihValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstPilihValueChanged

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        
        int nPilih = Integer.parseInt(txtTerpilih.getText());
        int i = cboAngkatan.getSelectedIndex();
        String isian = cboAngkatan.getSelectedItem().toString();
        
        //hitung biaya
        int  nPerMK = 0;
        switch (i) {
            case 0:nPerMK = 100000;break;
            case 1:nPerMK = 90000;break;
            case 2:nPerMK = 75000;break;
            default:nPerMK = 50000;
        }
        int nBiaya = nPilih * nPerMK;
        
        //Isikan Resume Ke txtArea Resume
        String sResume = "Anda Angkatan: " + isian + "\n" +
                         " Banyak Mata Kuliah Dipilih: " + Integer.toString(nPilih) + "\n" +
                         " Biaya per Mata Kuliah: " + Integer.toString(nPerMK) + "\n" +
                         " TOTAL BIAYA: " + Integer.toString(nBiaya);
        txtResume.setText(sResume);
    }//GEN-LAST:event_btnHitungActionPerformed

    private void lstKuliahValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstKuliahValueChanged
        // TODO add your handling code here:
        // Setiap diklik munculkan nama mata kuliah di txtKuliah
        int index = lstKuliah.getSelectedIndex();
        String kuliah = lstKuliah.getSelectedValue().toString();
        txtKuliah.setText(kuliah);
    }//GEN-LAST:event_lstKuliahValueChanged

    private void cboAngkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAngkatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboAngkatanActionPerformed

    private void txtKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKuliahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKuliahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FDaftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopy;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JComboBox<String> cboAngkatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstKuliah;
    private javax.swing.JList<String> lstPilih;
    private javax.swing.JTextField txtKuliah;
    private javax.swing.JTextArea txtResume;
    private javax.swing.JTextField txtTerpilih;
    // End of variables declaration//GEN-END:variables
}
